### ISSUE TITLE
Can't build with Qt 5.5 and Qt 5.6

### ISSUE THREAD

**Issue by shaoxie1986** [HamedMasafi/Noron#1]
..Noron-0.1-alpha\src\noronjsonbinaryserializer.cpp:136: error: no matching function for call to 'QObject::inherits(const QMetaObject_)'
         if(v.value<QObject_>()->inherits(&NoronPeer::staticMetaObject))

this is the error information.
                                                                      ^

**Comment by HamedMasafi** [comment]
Thanks for reporting.

This function was introduced in Qt 5.7.

Code will be compiled in v5.7. But I've changed code to compile with older versions. Next commit will be pushed in next days.

**Comment by HamedMasafi** [comment]
A draft was committed.
